# Generated by Django 5.2.17 on 2026-08-21 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='EventCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'event_calendar',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='event_calendar_date_range_idx')],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='merchants.category')),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=64)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_user',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_user', models.ForeignKey(db_column='merchant_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='merchants.merchantuser')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_key', models.CharField(max_length=64, unique=True)),
                ('merchant', models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='merchants.merchant')),
            ],
            options={
                'db_table': 'terminal',
            },
        ),
        migrations.AddIndex(
            model_name='merchantuser',
            index=models.Index(condition=models.Q(('locked_until__isnull', False)), fields=['locked_until'], name='merchant_user_locked_until_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['merchant_user', 'created_at'], name='audit_log_user_created_idx'),
        ),
    ]
