# Generated by Django 5.2.17 on 2026-08-21 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(max_length=32)),
                ('row_count', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingest_batch',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('headline', models.CharField(max_length=512)),
                ('body', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=32)),
                ('low_confidence_peer_set', models.BooleanField(default=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('agent_run_id', models.UUIDField(blank=True, null=True)),
                ('merchant', models.ForeignKey(db_column='merchant_id', on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='merchants.merchant')),
            ],
            options={
                'db_table': 'insight',
            },
        ),
        migrations.CreateModel(
            name='InsightAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_text', models.TextField()),
                ('priority', models.CharField(max_length=32)),
                ('sort_order', models.IntegerField()),
                ('insight', models.ForeignKey(db_column='insight_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analytics.insight')),
            ],
            options={
                'db_table': 'insight_action',
            },
        ),
        migrations.CreateModel(
            name='InsightProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('source_query_id', models.CharField(max_length=128)),
                ('clickhouse_sql', models.TextField()),
                ('query_params', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField()),
                ('result_summary', models.JSONField(default=dict)),
                ('ingest_batch', models.ForeignKey(db_column='ingest_batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='provenance_records', to='analytics.ingestbatch')),
                ('insight', models.ForeignKey(db_column='insight_id', on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='analytics.insight')),
            ],
            options={
                'db_table': 'insight_provenance',
            },
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['merchant', 'period_start', 'period_end', 'kind'], name='insight_merchant_period_idx'),
        ),
        migrations.AddIndex(
            model_name='insightprovenance',
            index=models.Index(fields=['insight', 'sequence'], name='insight_provenance_seq_idx'),
        ),
    ]
